# Generated by Django 5.0.2 on 2024-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.JSONField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('session_id', models.CharField(max_length=255)),
            ],
        ),
    ]
